on:
  issues:
    types: labeled
jobs:
  notify:
    if: ${{contains(github.event.issue.labels.*.name, 'early-adopter-review')}}
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: ${{format("{0}{1}", github.event.issue.title, github.event.pull_request.title)}}
      ISSUE_URL: ${{format("{0}{1}", github.event.issue.html_url, github.event.pull_request.html_url)}}
    steps:
      - name: Notify zulip interest group
        run: |
          pip3 install zulip
          env
          zulip-send \
            --site ${{secrets.ZULIP_SITE}} \
            --api-key ${{secrets.ZULIP_API_KEY}} \
            --user ${{secrets.ZULIP_USER}} \
            --stream ${{secrets.ZULIP_STREAM}} \
            --subject "Early Adopters: Review Request!" \
            --message "${ISSUE_TITLE} -- see ${ISSUE_URL}"
