on:
  issues:
    types: labeled
jobs:
  notify:
    if: ${{contains(github.event.issue.labels.*.name, 'early-adopter-review')}}
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: ${{github.event.issue.title}}
      ISSUE_URL: ${{github.event.issue.html_url}}
    steps:
      - name: Notify zulip interest group
        run: |
          pip3 install zulip
          zulip-send \
            --site $ZULIP_SITE \
            --api-key $ZULIP_API_KEY \
            --user $ZULIP_USER \
            --stream $ZULIP_STREAM \
            --subject "Early Adopters: Review Request!" \
            --message "${ISSUE_TITLE} -- see ${ISSUE_URL}"